### ISSUE TITLE
Error with starting the game

### ISSUE THREAD

**Issue by CastorF1ber** [GrowthcraftCE/Growthcraft-Deco#14]
![Jre-legacy Screenshot 2022 05 19 - 18 28 30 04](https://user-images.githubusercontent.com/85393018/169484910-bcca8574-47a8-457b-a53f-70065e65483d.png)
this errors don't give me to start the game. I downloaded this mod from Curse Forge. I have only Growthcraft (regular mod with milk, sellar...) and JEI.

**Comment by Alatyami** [comment]
Which version? 6.1.1 for MC 1.16?

**Comment by Alatyami** [comment]
Closing .... need to know which version of the mod was being used.
